### ISSUE TITLE
dataset labeling

### ISSUE THREAD

**Issue by shawnwbts** [Jiachi-Chen/TSE-ContractDefects#1]
Well,Sorry to bother you,can you tell me how to label these datasets?Just label these contracts manually one by one ?

**Comment by shawnwbts** [comment]
and if there any faster methods that we can use to label these contracts?

**Comment by Jiachi-Chen** [comment]
Yes, the results are based on manually labeling. It takes us a lot of time to label it : ). I think you can use some tools to label the smart contracts, e.g., Oyente, Mythil. However, there are some false positives / negatives of these tools.

**Comment by shawnwbts** [comment]
Thanks to your reply.And I read your open dataset, I found the most numerous vulnerability is COMPILE VERSION NOT FIXED ,not the high-risk vulnerabilities we think like overflow/underflow or reentrancy.So could you explain it to me? Thanks a lot!

**Comment by Jiachi-Chen** [comment]
For the details of the dataset, you can refer to our paper (https://arxiv.org/pdf/1905.01467). The smart contracts on this dataset are random selected from Ethereum. Thus, the distribution of the defects in our dataset is similar to the real-world smart contracts on Ethereum. It means in real-world Ethereum, most smart contracts have low-risk defects, and only a small number of contracts have high-risk vulnerabilities.
